"""Overseas status of players: who counts as "from outside the region" (the build greys them out and leaves them
out of the region counter). Written by derive.py next to users.jsonl as overseas_status.json.

A player is overseas when
  - their start.gg country is outside the region (scripts/<region>/country.py is_overseas_country), or
  - they are in manual/overseas_manual.json `uids` and have no country registration,
unless
  - they are in manual/overseas_manual.json `home_uids` (hand-kept: joke registrations, residents), or
  - they look like residents: at least RESIDENT_MIN_TOURNAMENTS offline 1on1 tournaments of this region within the last
    RESIDENT_WINDOW_DAYS days, spread over at least RESIDENT_MIN_MONTHS different months (scripts/<region>/classify.py).

The build (spsp) intersects `by_country` with the players it ranks and adds `manual` as is. Until 2026-09-28 the
build decided this itself from the previous build's player pages; moving it here makes it depend on the data only.
Attendance counts main events (not class brackets), after manual/user_merges.json.
"""
from __future__ import annotations

import datetime as dt
import json
import os
from pathlib import Path

OUT_NAME = "overseas_status.json"


def _load_json(path: Path, default):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return default


def load_merges(manual_dir: Path) -> dict[int, int]:
    """old uid -> final uid (chains A->B, B->C resolved)."""
    raw = _load_json(manual_dir / "user_merges.json", {}).get("merges") or []
    step = {int(m["old"]): int(m["new"]) for m in raw}
    out = {}
    for old in step:
        new, seen = step[old], {old}
        while new in step and new not in seen:
            seen.add(new)
            new = step[new]
        out[old] = new
    return out


def attendance(events_root: Path, since_iso: str, merges: dict[int, int]) -> dict[int, list[str]]:
    """uid -> dates (YYYY-MM-DD) of offline 1on1 main events on or after since_iso (one entry per event)."""
    out: dict[int, list[str]] = {}
    for dirpath, dirnames, filenames in os.walk(events_root):
        dirnames[:] = [d for d in dirnames if d != "class_phases"]   # class brackets repeat the main event's players
        if "derived.json" not in filenames or "standings.json" not in filenames:
            continue
        d = _load_json(Path(dirpath) / "derived.json", {})
        if not d.get("is_1on1") or d.get("is_offline") is False:
            continue
        date = (d.get("calendar") or {}).get("date")
        if not date or date < since_iso:
            continue
        st = _load_json(Path(dirpath) / "standings.json", [])
        st = st.get("data", []) if isinstance(st, dict) else st
        for u in {merges.get(r["user_id"], r["user_id"]) for r in st if r.get("user_id") is not None}:
            out.setdefault(u, []).append(date)
    return out


def build_status(clf, country_mod, users_path: Path, events_root: Path, manual_dir: Path, today: dt.date) -> dict:
    countries: dict[int, str] = {}
    with open(users_path, encoding="utf-8") as f:
        for line in f:
            try:
                u = json.loads(line)
            except Exception:
                continue
            if u.get("user_id") is not None and u.get("country"):
                countries[int(u["user_id"])] = u["country"]
    manual = _load_json(manual_dir / "overseas_manual.json", {})
    home = {int(u) for u in manual.get("home_uids") or []}
    by_country = {u for u, c in countries.items() if country_mod.is_overseas_country(c)} - home
    by_manual = {int(u) for u in manual.get("uids") or [] if int(u) not in countries} - home
    since = (today - dt.timedelta(days=clf.RESIDENT_WINDOW_DAYS)).isoformat()
    att = attendance(events_root, since, load_merges(manual_dir))

    def resident(u: int) -> bool:
        ds = att.get(u) or []
        return len(ds) >= clf.RESIDENT_MIN_TOURNAMENTS and len({x[:7] for x in ds}) >= clf.RESIDENT_MIN_MONTHS

    residents = {u for u in by_country | by_manual if resident(u)}
    return {
        "_comment": "Generated by scripts/common/derive.py (scripts/common/overseas.py). Do not edit; change "
                    "manual/overseas_manual.json or the region's RESIDENT_* constants instead.",
        "rule": {"window_days": clf.RESIDENT_WINDOW_DAYS, "min_tournaments": clf.RESIDENT_MIN_TOURNAMENTS,
                 "min_months": clf.RESIDENT_MIN_MONTHS},
        "by_country": sorted(by_country - residents),
        "manual": sorted(by_manual - residents),
        "resident": sorted(residents),
        "home": sorted(home),
    }


def write_overseas_status(clf, country_mod, region_dir: Path, events_root: Path, today: dt.date,
                          dry_run: bool = False) -> tuple[bool, dict]:
    """Write <region_dir>/overseas_status.json when the content changed. Returns (written, status)."""
    status = build_status(clf, country_mod, region_dir / "users.jsonl", events_root, region_dir / "manual", today)
    text = json.dumps(status, ensure_ascii=False, indent=1) + "\n"
    out = region_dir / OUT_NAME
    if out.exists() and out.read_text(encoding="utf-8") == text:
        return False, status
    if not dry_run:
        tmp = out.with_suffix(".json.tmp")
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, out)
    return True, status
