"""country (Japan) — start.gg の国名 (英語) を日本語表記にする表。

プレイヤーページの居住地表示と、海外タグの「国登録が日本以外か」の判定に使う。
2026-09-09 に spsp (spsp/country_ja.py) から移した。表記は日本語版 SSBU / 日本の一般表記に合わせる。
"""
from __future__ import annotations


COUNTRY_JA = {
    'United States': 'アメリカ',
    'Japan': '日本',
    'France': 'フランス',
    'Mexico': 'メキシコ',
    'Canada': 'カナダ',
    'Spain': 'スペイン',
    'Germany': 'ドイツ',
    'United Kingdom': 'イギリス',
    'Venezuela': 'ベネズエラ',
    'Australia': 'オーストラリア',
    'Chile': 'チリ',
    'Colombia': 'コロンビア',
    'Italy': 'イタリア',
    'Dominican Republic': 'ドミニカ共和国',
    'Switzerland': 'スイス',
    'Brazil': 'ブラジル',
    'China': '中国',
    'Norway': 'ノルウェー',
    'Peru': 'ペルー',
    'Sweden': 'スウェーデン',
    'Netherlands': 'オランダ',
    'Austria': 'オーストリア',
    'El Salvador': 'エルサルバドル',
    'Belgium': 'ベルギー',
    'Puerto Rico': 'プエルトリコ',
    'Guatemala': 'グアテマラ',
    'Ireland': 'アイルランド',
    'Honduras': 'ホンジュラス',
    'Finland': 'フィンランド',
    'Argentina': 'アルゼンチン',
    'New Zealand': 'ニュージーランド',
    'South Korea': '韓国',
    'Russia': 'ロシア',
    'Singapore': 'シンガポール',
    'Panama': 'パナマ',
    'Madagascar': 'マダガスカル',
    'India': 'インド',
    'Costa Rica': 'コスタリカ',
    'Portugal': 'ポルトガル',
    'Ecuador': 'エクアドル',
    'Uruguay': 'ウルグアイ',
    'Nicaragua': 'ニカラグア',
    'England': 'イングランド',
    'Taiwan': '台湾',
    'United States Virgin Islands': 'アメリカ領ヴァージン諸島',
    'Hong Kong': '香港',
    'Greece': 'ギリシャ',
    'Israel': 'イスラエル',
    'Indonesia': 'インドネシア',
    'Denmark': 'デンマーク',
    'Bolivia': 'ボリビア',
    'Saudi Arabia': 'サウジアラビア',
    'Scotland': 'スコットランド',
    'Morocco': 'モロッコ',
    'Wales': 'ウェールズ',
    'United Arab Emirates': 'アラブ首長国連邦',
    'Cyprus': 'キプロス',
    'Paraguay': 'パラグアイ',
    'Iceland': 'アイスランド',
    'Luxembourg': 'ルクセンブルク',
    'Thailand': 'タイ',
    'Philippines': 'フィリピン',
    'Hungary': 'ハンガリー',
    'United States Minor Outlying Islands': '合衆国領有小離島',
    'Algeria': 'アルジェリア',
    'Qatar': 'カタール',
    'South Africa': '南アフリカ',
    'French Guiana': 'フランス領ギアナ',
    'Malaysia': 'マレーシア',
    'Poland': 'ポーランド',
    'Georgia': 'ジョージア',
    'Egypt': 'エジプト',
    'Jamaica': 'ジャマイカ',
    'Antarctica': '南極',
    'Réunion': 'レユニオン',
    'North Korea': '北朝鮮',
    'Lebanon': 'レバノン',
    'Azerbaijan': 'アゼルバイジャン',
    'Vietnam': 'ベトナム',
    'Aruba': 'アルバ',
    'Isle of Man': 'マン島',
    'Turkey': 'トルコ',
    'Albania': 'アルバニア',
    'Afghanistan': 'アフガニスタン',
    'Jordan': 'ヨルダン',
    'Cuba': 'キューバ',
    'Kuwait': 'クウェート',
    'Ukraine': 'ウクライナ',
    'Tunisia': 'チュニジア',
    'Åland Islands': 'オーランド諸島',
    'Guam': 'グアム',
    'Jersey': 'ジャージー',
    'Northern Mariana Islands': '北マリアナ諸島',
    'Bahamas': 'バハマ',
    'Trinidad and Tobago': 'トリニダード・トバゴ',
    'American Samoa': 'アメリカ領サモア',
    'Vatican City': 'バチカン市国',
    'Chad': 'チャド',
    'Kazakhstan': 'カザフスタン',
    'Uzbekistan': 'ウズベキスタン',
    'Anguilla': 'アンギラ',
    'Serbia': 'セルビア',
    'Romania': 'ルーマニア',
    'San Marino': 'サンマリノ',
    'Armenia': 'アルメニア',
    'Pakistan': 'パキスタン',
    'Martinique': 'マルティニーク',
    'Antigua and Barbuda': 'アンティグア・バーブーダ',
    'Angola': 'アンゴラ',
    'Liechtenstein': 'リヒテンシュタイン',
    'Mongolia': 'モンゴル',
    'Nigeria': 'ナイジェリア',
    'Guadeloupe': 'グアドループ',
    'Estonia': 'エストニア',
    'Bulgaria': 'ブルガリア',
    'Slovakia': 'スロバキア',
    'Barbados': 'バルバドス',
    'Andorra': 'アンドラ',
    'Dominica': 'ドミニカ国',
    'Kenya': 'ケニア',
    'Libya': 'リビア',
    'New Caledonia': 'ニューカレドニア',
    'Belize': 'ベリーズ',
    'Nepal': 'ネパール',
    'Bosnia and Herzegovina': 'ボスニア・ヘルツェゴビナ',
    'Niger': 'ニジェール',
    'Lithuania': 'リトアニア',
    'DR Congo': 'コンゴ民主共和国',
    'Guernsey': 'ガーンジー',
    'Macau': 'マカオ',
    'Kosovo': 'コソボ',
    'Christmas Island': 'クリスマス島',
    'Sri Lanka': 'スリランカ',
    'Czech Republic': 'チェコ',
    'Greenland': 'グリーンランド',
    'Burkina Faso': 'ブルキナファソ',
    'Iran': 'イラン',
    'Zimbabwe': 'ジンバブエ',
    'Heard Island and McDonald Islands': 'ハード島とマクドナルド諸島',
    'Wallis and Futuna': 'ウォリス・フツナ',
    'French Polynesia': 'フランス領ポリネシア',
    'Zambia': 'ザンビア',
    'Marshall Islands': 'マーシャル諸島',
    'Gibraltar': 'ジブラルタル',
    'Ghana': 'ガーナ',
    'Djibouti': 'ジブチ',
    'Togo': 'トーゴ',
    'Suriname': 'スリナム',
    'Saint Vincent and the Grenadines': 'セントビンセント・グレナディーン',
    'Cambodia': 'カンボジア',
    'Syria': 'シリア',
    'Kiribati': 'キリバス',
    'Bahrain': 'バーレーン',
    'Palestine': 'パレスチナ',
    'Ethiopia': 'エチオピア',
    'Western Sahara': '西サハラ',
    'Micronesia': 'ミクロネシア連邦',
    'Myanmar': 'ミャンマー',
    'Malawi': 'マラウイ',
    'Senegal': 'セネガル',
    'Saint Pierre and Miquelon': 'サンピエール島・ミクロン島',
    'Fiji': 'フィジー',
    'Haiti': 'ハイチ',
    'Cameroon': 'カメルーン',
    'Belarus': 'ベラルーシ',
    'Brunei': 'ブルネイ',
    'Cook Islands': 'クック諸島',
    'Ivory Coast': 'コートジボワール',
    'Botswana': 'ボツワナ',
    'Bermuda': 'バミューダ',
    'Equatorial Guinea': '赤道ギニア',
    'Monaco': 'モナコ',
    'Cape Verde': 'カーボベルデ',
    'Oman': 'オマーン',
    'Svalbard and Jan Mayen': 'スヴァールバル諸島・ヤンマイエン島',
    'Laos': 'ラオス',
    'Yemen': 'イエメン',
    'Mozambique': 'モザンビーク',
    'French Southern and Antarctic Lands': 'フランス領南方・南極地域',
    'Cocos (Keeling) Islands': 'ココス諸島',
    'Namibia': 'ナミビア',
}




def country_ja(name: str | None) -> str | None:
    """英語国名 → 日本語国名 (未収録はそのまま返す)。"""
    if not name:
        return None
    return COUNTRY_JA.get(name, name)


def is_overseas_country(country: str | None) -> bool:
    """start.gg の国登録が日本以外か (未登録は False = 判断しない)。"""
    return bool(country) and country != 'Japan'
